install:
 - pip install -r requirements-travis.txt
language: python
python:
 - 3.4
 - 3.5
 - 3.6
 - 3.7-dev
script:
 - coverage run tests.py -a
 - flake8 tempvars
 - echo $TRAVIS_PYTHON_VERSION | grep -e '^3\.6' && codecov || echo "No codecov."
 - sh -c 'cd doc; make doctest'

